#file: noinspection ComposeUnknownKeys
name: eclipse-app
recipe: laravel
config:
  webroot: public
  php: '8.3'
  via: nginx
  database: mariadb:10.11
  cache: redis
services:
  appserver:
    type: php:custom
    config:
      php: .lando/php.ini
    environment:
      TZ: "Europe/Ljubljana"
    xdebug: "debug,develop,coverage"
    overrides:
      image: slimdeluxe/php:8.3-v1.1
    build_as_root:
      - apt-get install supervisor -y
      - cp -f /app/.lando/entrypoint.sh /usr/local/bin/docker-php-entrypoint
      - cp -f /app/.lando/horizon.conf /etc/supervisor/conf.d/horizon.conf
    run_as_root:
      - service supervisor start
      - supervisorctl start horizon:*
    run:
      # These commands run when the app is rebuilt
      - php artisan migrate:fresh --seed
      - npm install
      - npm run build
    ports:
      # Port forwarding for "npm run dev"
      - "3009:3009"
  database:
    creds:
      database: eclipse
      user: developer
      password: developer
  pma:
    type: phpmyadmin
    hosts:
      - database
    database:
      type: mariadb:10.11
proxy:
  pma:
    - pma.eclipse-app.lndo.site
tooling:
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
  format:
    service: appserver
    description: Fix code style issues
    cmd: "composer format"
  npm:
    service: appserver
