#file: noinspection ComposeUnknownKeys,YAMLSchemaValidation
name: eclipse-app
recipe: laravel
config:
  webroot: public
  php: '8.3'
  via: nginx
  database: mariadb:10.11
  cache: redis
services:
  appserver:
    type: php:custom
    config:
      php: .lando/php.ini
    environment:
      TZ: "Europe/Ljubljana"
    xdebug: "debug,develop,coverage"
    overrides:
      image: slimdeluxe/php:8.3-v1.2
    build_as_root:
      # Copy supervisor configs
      - cp -f /app/.lando/*.conf /etc/supervisor/conf.d/
    run:
      # These commands run when the app is rebuilt
      - php artisan migrate:fresh --seed
      - npm install
      - npm run build
      - crontab /app/.lando/cron
    ports:
      # Port forwarding for "npm run dev"
      - "3009:3009"
      - "8080:8080"
  appserver_nginx:
    # Set scanner to admin/login page and not the root, to prevent 403 error
    scanner:
      path: /admin/login
      retry: 5
  database:
    creds:
      database: eclipse
      user: developer
      password: developer
  pma:
    type: phpmyadmin
    hosts:
      - database
    database:
      type: mariadb:10.11
    overrides:
      image: phpmyadmin
  typesense:
    type: typesense:28.0
    portforward: 8108
    apiKey: abc
proxy:
  pma:
    - pma.eclipse-app.lndo.site
  appserver:
    - ws.eclipse-app.lndo.site:8080
events:
  post-start:
    - sudo service supervisor start
    - sudo service cron start
    - php artisan telescope:prune
tooling:
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
  format:
    service: appserver
    description: Fix code style issues
    cmd: "composer format"
  npm:
    service: appserver
